##begin config
version 0.1
residentpri 88
libbase VC4Base
libbasetype struct VC4Base
##end config

##begin cdef
#include <inttypes.h>

#define VC4_PARAM_V3D_IDENT0                 0
#define VC4_PARAM_V3D_IDENT1                 1
#define VC4_PARAM_V3D_IDENT2                 2
#define VC4_PARAM_SUPPORTS_BRANCHES          3
#define VC4_PARAM_SUPPORTS_ETC1              4
#define VC4_PARAM_SUPPORTS_THREADED_FS       5
#define VC4_PARAM_SUPPORTS_FIXED_RCL_ORDER   6
#define VC4_PARAM_SUPPORTS_MADVISE           7
#define VC4_PARAM_SUPPORTS_PERFMON           8

#define VC4_BOF_NOINIT                       (1U << 0)
#define VC4_BOF_SHADER                       (1U << 1)

#define VC4_SYNC_CPU_TO_GPU                  0
#define VC4_SYNC_GPU_TO_CPU                  1

#define VC4_SUBMIT_USE_CLEAR_COLOR           (1U << 0)
#define VC4_SUBMIT_FIXED_RCL_ORDER            (1U << 1)
#define VC4_SUBMIT_RCL_ORDER_INCREASING_X     (1U << 2)
#define VC4_SUBMIT_RCL_ORDER_INCREASING_Y     (1U << 3)

#define VC4_SUBMIT_ERR_INVALID               (-1)
#define VC4_SUBMIT_ERR_NOT_IMPLEMENTED       (-2)

struct VC4SubmitRCLSurface
{
    uint32_t hindex;
    uint32_t offset;
    uint16_t bits;
    uint16_t flags;
};

struct VC4SubmitCL
{
    uint64_t bin_cl;
    uint64_t shader_rec;
    uint64_t uniforms;
    uint64_t bo_handles;
    uint32_t bin_cl_size;
    uint32_t shader_rec_size;
    uint32_t shader_rec_count;
    uint32_t uniforms_size;
    uint32_t bo_handle_count;
    uint16_t width;
    uint16_t height;
    uint8_t min_x_tile;
    uint8_t min_y_tile;
    uint8_t max_x_tile;
    uint8_t max_y_tile;
    struct VC4SubmitRCLSurface color_read;
    struct VC4SubmitRCLSurface color_write;
    struct VC4SubmitRCLSurface zs_read;
    struct VC4SubmitRCLSurface zs_write;
    struct VC4SubmitRCLSurface msaa_color_write;
    struct VC4SubmitRCLSurface msaa_zs_write;
    uint32_t clear_color[2];
    uint32_t clear_z;
    uint8_t clear_s;
    uint8_t pad[3];
    uint32_t flags;
    uint64_t seqno;
    uint32_t perfmonid;
    uint32_t in_sync;
    uint32_t out_sync;
    uint32_t pad2;
};
##end cdef

##begin cdefprivate
#include "vc4_private.h"
##end cdefprivate

##begin functionlist
int VC4GetParam(unsigned int param, uint64_t *value) (D0, A0)
int VC4CreateBO(unsigned int size, unsigned int alignment, unsigned int flags, unsigned int *handle) (D0, D1, D2, A0)
int VC4MapBO(unsigned int handle, void **cpu_address, unsigned int *bus_address, unsigned int *size) (D0, A0, A1, A2)
int VC4FreeBO(unsigned int handle) (D0)
int VC4SyncBO(unsigned int handle, unsigned int offset, unsigned int length, unsigned int direction) (D0, D1, D2, D3)
int VC4ValidateSubmitCL(const struct VC4SubmitCL *submit) (A0)
##end functionlist
